name: Ken Corsini
favicon: null
layout_spectrum: 0.33897579251788557
typography_spectrum: 0.7589224427938461
title: Ken Corsini
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.054427937138825655
purpose: []
